### ISSUE TITLE
Mirror solidus branches to support extension Gemfiles

### ISSUE THREAD

**Issue by elia** [solidusio/solidus_frontend#10]
Many extensions now have some version of the following code in their gemfile:

```rb
branch = ENV.fetch('SOLIDUS_BRANCH', 'master')
solidus_git, solidus_frontend_git = 
  if (branch == 'master') || (branch >= 'v3.2')
    %w[solidusio/solidus solidusio/solidus_frontend]
  else
    %w[solidusio/solidus] * 2
  end
gem 'solidus', github: solidus_git, branch: branch
gem 'solidus_frontend', github: solidus_frontend_git, branch: branch
```

This means that if the solidus branch is not set to `master` bundler will try to load the corresponding branch in this repo.

I think branches for the currently supported versions of solidus should be created, or alternatively, we need to update the mechanism we use to load the proper frontend inside extensions.

**Comment by waiting-for-dev** [comment]
Unless I'm missing something, we only need the v3.2 branch in this repository, as for previous ones the `solidusio/solidus` repository will be used. I just [created it](https://github.com/solidusio/solidus_frontend/tree/v3.2).

Can we close this issue or do you think there's something else to do?

**Comment by elia** [comment]
I think we're good, in _solidus_dev_support_ I changed the Gemfile template to only use the git version of solidus frontend when running from master, otherwise it will rely on ruby gems to sort out the best version 👍
