### ISSUE TITLE
Frontend styles are inconsistent in Chrome and Firefox

### ISSUE THREAD

**Issue by jacobherrington** [solidusio/solidus_frontend#12]
A significant amount of the styles don't match up at all in Chrome and Firefox. It might be a good idea to get the styles more consistent in standard browsers.

It's important that the Fronted shows a good example of what Solidus can achieve as potential adopters are likely to check out the stock frontend before making the decision to use Solidus.

Here is a good example, specifically the Order Summary:
(Chrome)
<img width="1662" alt="screen shot 2018-10-01 at 10 24 39 am" src="https://user-images.githubusercontent.com/11466782/46298436-a165b980-c564-11e8-853e-960872dad465.png">

(Firefox)
![image](https://user-images.githubusercontent.com/11466782/46298462-b2162f80-c564-11e8-8738-092fdea6f23f.png)

**Comment by fthobe** [comment]
@kennyadsl can be closed.
