### ISSUE TITLE
Adding Locale in URL with routing-filter gem crash the app

### ISSUE THREAD

**Issue by wljg** [solidusio/solidus_frontend#5]
using solidus_i18n and routing-filter gem :

Rails.application.routes.draw do
  filter :locale
...

i get NoMethodError in Spree::Home#index undefined method `map' for #<ActionDispatch::Journey::Formatter::RouteWithParams:0x00007f9488027438>

**Comment by kennyadsl** [comment]
Hey @wljg, which version of the `routing-filter` gem are you using?

**Comment by wljg** [comment]
v 0.6.3 but sorry, i opened the issue in the wrong repo, the issue is with solidus_starter_frontend

**Comment by kennyadsl** [comment]
I see, by the way, `routing-filter` 0.7.x is the only version compatible with Rails 6.1+. Maybe that's the issue?

**Comment by kennyadsl** [comment]
Closing this, feel free to reopen it on the other repository if it still doesn't work!
